name: smoothie
description: Create and sample a cmooth bezier curve going through a given set of points
version: 0.1.2
homepage: https://github.com/alekskuzmin/smoothie

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bezier: ^1.1.5
  vector_math: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: